services:
  bot:
    container_name: funka-discord-bot
    build: 
      context: ./
      target: dev-runner
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - ./.env
    networks:
      - kinkeeper-private

networks:
  kinkeeper-private: